#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LT, DIR_RT, DIR_END };

enum SCENEID { SC_MENU, SC_STAGE1, SC_STAGE2, SC_STAGE3, SC_STAGE4, SC_END };

enum OBJID { OBJ_PLAYER, OBJ_MOUSE, OBJ_MONSTER, OBJ_BULLET, OBJ_TOWER, OBJ_ITEM, OBJ_BLOCK, OBJ_BUTTON, OBJ_END };

enum TOWERTYPE {TOWER_NORMAL , TOWER_HEART , TOWER_END};
